server:
  error:
    whitelabel:
      enabled:
        false    path:
          /error  forward-headers-strategy:
            framework  port:
              8080spring:
                application:
                  name:
                    malio-example  devtools:
                      restart:
                        additional-exclude:
                          launcherDir/**    add-properties:
                            false  jackson:
                              date-format:
                                yyyy-MM-dd'T'HH:mm:ss.SSSZ    serialization:
                                  write_dates_as_timestamps:
                                    false  output:
                                      ansi:
                                        enabled:
                                          detect  servlet:
                                            multipart:
                                              max-file-size:
                                                20MB      max-request-size:
                                                  20MB  web:
                                                    resources:
                                                      static-locations:
                                                        classpath:/launcherDir/,classpath:/public/debug:
                                                          falselogging:
                                                            level:
                                                              web:
                                                                info    root:
                                                                  info  pattern:
                                                                    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'