package com.github.nalukit.malio.processor.model;

public enum ConstraintType {
  MAX_VALUE_CONSTRAINT,
  MIN_VALUE_CONSTRAINT,
  BLACKLIST_CONSTRAINT,
  WHITELIST_CONSTRAINT,
  REGEXP_CONSTRAINT,
  MAX_LENGTH_CONSTRAINT,
  MIN_LENGTH_CONSTRAINT,
  NOT_NULL_CONSTRAINT
}
