package com.github.nalukit.malio.processor.model;

public enum ConstraintType {
  MAX_VALUE_CONSTRAINT,
  MIN_VALUE_CONSTRAINT,
  BLACKLIST_CONSTRAINT,
  WHITELIST_CONSTRAINT,
  REGEXP_CONSTRAINT,
  MAX_LENGTH_CONSTRAINT,
  MIN_LENGTH_CONSTRAINT,
    EMAIL_CONSTRAINT, MAX_DECIMAL_VALUE_CONSTRAINT, MIN_DECIMAL_VALUE_CONSTRAINT, NOT_BLANK_CONSTRAINT, NOT_EMPTY_CONSTRAINT, SIZE_CONSTRAINT, NOT_NULL_CONSTRAINT
}
